http_addr=":8080"
https_addr=""
management_addr="127.0.0.1:8090"
http_redirect=false
letsencrypt_email=""
https_domain-whitelist=["evepraisal.com"]

base-url="http://127.0.0.1:8080"

ad-block=""
extra-js=""

db_path="db/"
backup_path="db/backups/"

newrelic_app-name="Evepraisal"
newrelic_license-key=""

esi_baseurl="https://esi.evetech.net/latest"
sso-authorize-url="https://login.eveonline.com/oauth/authorize"
sso-verify-url="https://login.eveonline.com/oauth/verify"
sso-token-url="https://login.eveonline.com/oauth/token"
