[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  branch = "master"
  name = "github.com/blevesearch/bleve"

[[constraint]]
  branch = "master"
  name = "github.com/boltdb/bolt"

[[constraint]]
  name = "github.com/davecgh/go-spew"
  version = "1.1.0"

[[constraint]]
  branch = "master"
  name = "github.com/dietsche/rfsnotify"

[[constraint]]
  branch = "master"
  name = "github.com/dustin/go-humanize"

[[constraint]]
  branch = "master"
  name = "github.com/gorilla/context"

[[constraint]]
  branch = "master"
  name = "github.com/gorilla/securecookie"

[[constraint]]
  branch = "master"
  name = "github.com/gorilla/sessions"

[[constraint]]
  branch = "master"
  name = "github.com/martinlindhe/base36"

[[constraint]]
  branch = "master"
  name = "github.com/mash/go-accesslog"

[[constraint]]
  branch = "master"
  name = "github.com/newrelic/go-agent"

[[constraint]]
  branch = "master"
  name = "github.com/spf13/viper"

[[constraint]]
  branch = "master"
  name = "golang.org/x/crypto"

[[constraint]]
  version = "v1.4.2"
  name = "gopkg.in/fsnotify.v1"

[[constraint]]
  name = "gopkg.in/yaml.v2"
  source = "https://github.com/go-yaml/yaml.git"
  branch = "v2"

[[constraint]]
  branch = "master"
  name = "github.com/sethgrid/pester"

[[constraint]]
  version = "1.2"
  name = "github.com/go-zoo/bone"

[[constraint]]
  version = "v0.2"
  name = "github.com/leekchan/accounting"

[[constraint]]
  name = "github.com/mssola/user_agent"
  version = "0.4.1"
